using System;

namespace Executive.API
{
    
    /// <summary>
    /// The central api for the executive.
    /// Deals with execution of a command after its trigger has been run.
    /// </summary>
    public interface IAction
    {
        /// <summary>
        /// The id of the action.
        /// Autogenerated and unique.
        /// </summary>
        Guid Id { get; }

        /// <summary>
        /// The name of a given action.
        /// User-defined, unique for a given user.
        /// </summary>
        string Name { get; }
        
        /// <summary>
        /// The sourcecode of a n <see cref="IAction"/>.
        /// Is executed by the CSharp scripting engine together with the parameters and several
        /// other external components provided by the executive to perform the command.
        /// </summary>
        string Source { get; set; }
    }
}