using System;

namespace Executive.Implementation
{
    
    /// <summary>
    /// The central api for the executive.
    /// Deals with execution of a command after its trigger has been run.
    /// </summary>
    public class Action
    {
        public Action(string name, string source)
        {
            Name = name;
            Source = source;
        }

        /// <summary>
        /// The id of the action.
        /// Autogenerated and unique.
        /// </summary>
        public Guid Id { get; } = Guid.NewGuid();

        /// <summary>
        /// The name of a given action.
        /// User-defined, unique for a given user.
        /// </summary>
        public string Name { get; }
        
        /// <summary>
        /// The sourcecode of a n <see cref="Action"/>.
        /// Is executed by the CSharp scripting engine together with the parameters and several
        /// other external components provided by the executive to perform the command.
        /// </summary>
        public string Source { get; set; }
    }
}